### ISSUE TITLE
After syncing a project the resource instance list and map do not immediately update

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#159]
Once a user syncs a project from the projects instances tab, they have to navigate out of that project and return to the resource instance list or map, to see the loaded instances.

**Comment by apeters** [comment]
This doesn't seem to be the case anymore with the list.  @chiatt can you confirm that this is still an issue?

**Comment by chiatt** [comment]
This should be resolved for the resource instance list. Ticket #325 addresses the map portion of this issue and should probably be resolved with other pending map related issues.

**Comment by apeters** [comment]
I'll say that this is partially resolved and the #325 should address the map portion of this ticket
